[tool.poetry]
name = "mpl_bsic"
version = "1.1.16"
description = "BSIC Plotting Library"
authors = ["Andrea Franceschini <andrea.franceschini2@studbocconi.it>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9"
matplotlib = "^3.8.0"
numpy = "^1.26.0"
pandas = "^2.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
